# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Bettercap Add-on
version: "1.3.0"
slug: bettercap
description: An add-on that exposes Bettercap
url: "https://github.com/matthewturk/bettercap-hass-addon/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
#image: "ghcr.io/home-assistant/{arch}-addon-example"
ports:
  8083/tcp: 8083
  443/tcp: 443